from typing import Protocol

from common.schemas.assignments import WorkAssignment
from common.schemas.workers import RuntimeCapabilities


class ExecutionBackend(Protocol):
    """Operations used by the one-attempt execution coordinator."""
    engine: str

    async def ensure_image(self, image: str) -> str: ...
    async def create(self, assignment: WorkAssignment, image_id: str) -> None: ...
    async def start(self) -> None: ...
    async def wait(self) -> int: ...
    async def stop(self) -> None: ...
    async def kill(self) -> None: ...
    async def terminate(self) -> None: ...
    async def logs(self): ...
    async def inspect(self) -> dict: ...
    async def cleanup(self) -> None: ...


class Executor(Protocol):
    """Runtime boundary; engine selection and implementation remain internal."""

    async def capabilities(self) -> RuntimeCapabilities: ...
    async def select(self) -> ExecutionBackend: ...
